name: Create Release and Upload Binaries

on:
  push:
    tags:
      - 'v*' # Push events to tags matching v*, e.g. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Update apt sources for EOL Debian Buster
        run: |
          echo "deb http://archive.debian.org/debian/ buster main contrib non-free" > /etc/apt/sources.list
          echo "deb http://archive.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list
          echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until

      - name: Install Build Dependencies
        run: |
          apt-get update
          apt-get install -y wget build-essential libssl-dev zlib1g-dev \
            libbz2-dev libreadline-dev libsqlite3-dev curl llvm \
            libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev \
            liblzma-dev git pkg-config

      - name: Build and Install Python 3.12
        run: |
          wget https://www.python.org/ftp/python/3.12.4/Python-3.12.4.tgz
          tar -xf Python-3.12.4.tgz
          cd Python-3.12.4
          ./configure --enable-optimizations
          make -j$(nproc)
          make install
          cd ..
          rm -rf Python-3.12.4 Python-3.12.4.tgz

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install cython numpy
          pip3 install .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build executable with PyInstaller
        run: pyinstaller RawAlchemy.spec

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RawAlchemy-linux
          path: dist/RawAlchemy

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux]
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Artifacts for Release
        run: |
          tag="${{ github.ref_name }}"
          mv artifacts/RawAlchemy-linux/RawAlchemy "RawAlchemy-${tag}-linux"
        shell: bash

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            RawAlchemy-*-linux
